<?php
include_once __DIR__ . '/../includes/settings.php';

if (isset($_GET['id'])) {$file_id = $_GET['id'];
}

$stmt = $conn->prepare('SELECT * FROM files WHERE file_id = :file_id');
$stmt->execute(array(':file_id' => $file_id));
$file = $stmt->fetch(PDO::FETCH_ASSOC);

?>

<!DOCTYPE html>
<html>

<head><title>File Download</title><link rel="icon" type="image/png" href="./favicon.ico"><meta name="viewport" content="width=device-width, initial-scale=1"><!-- Bootstrap CSS link --><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"><style>    /* Custom styles */    body {        padding-bottom: 70px;        padding: 20px;        /*display: flex;        justify-content: center;        align-items: center;*/        height: 100vh;        margin: 0;    }
    p {        margin-top: 0px;        margin-bottom: 5px;    }
    .preview-container {        text-align: center;        overflow: auto;        /* Добавляем прокрутку */        max-width: 100%;        /* Ограничиваем максимальную ширину для прокрутки */        max-height: 70vh;        /* Ограничиваем максимальную высоту для прокрутки */        margin-bottom: 15px;        /* Добавляем нижний отступ, чтобы избежать перекрытия других элементов */    }

    .preview-container .card {        display: inline-block;        text-align: left;        width: auto;    }
    .download-button {        width: 3in;        display: block;        margin: 0 auto;    }
    .thumbnail-image {        max-width: 100%;        max-height: 80vh;        cursor: pointer;        /* Добавим указатель для индикации возможности клика */    }</style>
</head>

<body><div class="container">    <h1 class="mt-4">Download File</h1>
    <?php if ($file): ?>        <div class="preview-container justify-content-center">            <div class="card my-4">                <div class="card-body">                    <h5 class="card-title">File Name:                        <?php echo $file['file_name'] . " | ID: " . $file['origin_file_id']; ?>                    </h5>                    <p class="card-text">File Size:                        <?php                        $fileSizeInBits = $file['file_size'];
                        if ($fileSizeInBits < 1048576) {                            $fileSizeInKilobytes = $fileSizeInBits / 1024; // 1,024 bits = 1 KB                            $fileSizeInKilobytesRounded = round($fileSizeInKilobytes, 2); // Rounded to two decimal places                                                if ($fileSizeInKilobytes < 1) {                                echo $fileSizeInBits . " bytes";                            } else {                                echo $fileSizeInKilobytesRounded . " KB";                            }                        } else {                            $fileSizeInMegabytes = $fileSizeInBits / 1048576; // 1,048,576 bits = 1 MB                            $fileSizeInMegabytesRounded = round($fileSizeInMegabytes, 2); // Rounded to two decimal places                                                echo $fileSizeInMegabytesRounded . " MB";                        }                        ?>                    </p>                    <p class="card-text" id="timer">Pre-deletion: 6d 23h 59m 59s</p>                    <p class="card-text">                        <?php                        // Получение даты загрузки файла из временной метки (timestamp)                        $uploadDate = $file["date"]; // Предположим, что это временная метка UNIX
                        // Рассчитываем дату удаления файла на основе времени до удаления                        $timeToDeletion =                            $file["date"] + $dayto * 24 * 60 * 60; // $dayto - предполагаемая переменная с количеством дней до удаления файла
                        // Преобразуем временные метки в формат Y-m-d для использования в запросе к API                        $fromDate = date("Y-m-d", $uploadDate);                        $toDate = date("Y-m-d", $timeToDeletion);
                        // Создаем URL запроса к API с учетом временного интервала                        $api_url = "https://ytics.fy.webs.nf/api/v1/stats/10?name=page&per_page=100&from=$fromDate&to=$toDate";
                        $api_key =                            "WKDRKItubVZNcTWirjvlDnD4F8N5iXVOQHlPtqasb7RjUCIh8xGKuoDet1DOQhDB"; // Замените YOUR_API_KEY на ваш API ключ
                        $ch = curl_init($api_url);                        curl_setopt($ch, CURLOPT_HTTPHEADER, [                            "Accept: application/json",                            "Authorization: Bearer " . $api_key,                        ]);                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);                        $response = curl_exec($ch);
                        if (curl_getinfo($ch, CURLINFO_HTTP_CODE) === 200) {                            $data = json_decode($response, true);
                            // Обработка данных: просмотры для данного файла                            $file_views = 0;                            foreach ($data["data"] as $item) {                                if (                                    $item["value"] ===                                    "/file?id=" . $file_id                                ) {                                    $file_views = $item["count"];                                    break;                                }                            }
                            // Отображение количества просмотров на странице                            echo "File Views: $file_views";
                        } else {                            echo "Failed to fetch views data.";                        }                        ?>                    </p>                    <p class="card-text">Preview:</p>


                    <!-- Add a preview section based on the file type -->                    <?php                    $fileType = pathinfo($file['file_name'], PATHINFO_EXTENSION);                    if (in_array($fileType, ['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'avif', 'apng'])) {                        echo '<img class="thumbnail-image img-fluid" src="site.com' . $file['file_dir'] . '/' . $file['file_name'] . '" alt="File Preview">';                    } elseif (in_array($fileType, ['mp4', 'mov', 'ogg', 'webm', 'mkv', 'flv', 'avi', 'm4v'])) {                        echo '<video controls>                        <source src="site.com' . $file['file_dir'] . '/' . $file['file_name'] . '"alt="File Preview">                          <div class="alert alert-warning" role="alert">Your browser does not support the video preview.</div>                          </video>';                    } elseif (in_array($fileType, ['m4a', 'flac', 'mp3', 'wav', 'aac', 'wma'])) {                        echo '<audio controls>                        <source src="site.com' . $file['file_dir'] . '/' . $file['file_name'] . '" alt="File Preview">                          <div class="alert alert-warning" role="alert">Your browser does not support the video preview.</div>                          </audio>';                    } elseif (in_array($fileType, ['doc', 'docx', 'dot', 'html', 'txt', 'rtf', 'odt', 'pdf', 'pages', 'xps', 'dotx', 'ott', 'psw', 'prn', 'stw', 'vor', 'uot', 'xml', 'xls', 'xlsx', 'sdc', 'csv', 'chm', 'dbf', 'dif', 'djvu', 'hlp', 'ods', 'ots', 'pxl', 'sdc', 'stc', 'sxc', 'slk', 'uos', 'xlt', 'xls', 'xlsm', 'ppt', 'pptx', 'sdd', 'sxi', 'odg', 'odp', 'otp', 'pot', 'pptm', 'ppsx', 'sdd', 'sda', 'sti', 'uop', 'dfx', 'eps', 'psd', 'ps', 'svg', 'tif', 'ttf', 'ai', 'bpm', 'dwg', 'emf', 'eot', 'fxg', 'met', 'otf', 'pbm', 'pct', 'pgm', 'ppm', 'pwp', 'ras', 'svm', 'swf', 'sxd', 'svgz', 'jpf', 'psb', 'raw', 'sct', 'woff', 'zip'])) {                        echo '<iframe src="http://docs.google.com/gview?url=site.com' . $file['file_dir'] . '/' . $file['file_name'] . '&embedded=true" 
style="max-width:650px; max-height:650px; width:500px; height:550px;" frameborder="0"></iframe>';                    } else {                        // Handle other file types (videos, documents, etc.) as needed                        echo '<div class="alert alert-warning" role="alert">Preview not available for this file type.</div>';                    }                    ?>
                <!-- Обновленный блок кнопки скачивания -->                <div id="download-section">                    <a class="btn btn-primary mt-3 download-button" id="downloadLink"                        href="site.com<?php echo $file['file_dir'] . '/' . $file['file_name']; ?>"                        download>Download</a>                </div>                </div><script type="text/javascript" src="https://adzly.com/adserve/getadzly.php?awid=14353"></script>
<noscript><a href="https://adzly.com/r/92284">Put your ad here for free! - adzly.com</a></noscript>            </div>        </div><?php include 'report.php'; ?>    <?php else: ?>        <div class="alert alert-danger" role="alert">            File not found.        </div>    <?php endif; ?></div><!-- Footer section --><footer class="footer mt-auto py-2 bg-light text-center">    <div class="container">        <div class="my-2">            <a href="https://site.com"><button class="btn btn-secondary btn-sm mx-1">Home</button></a>            <a href="https://site.com/stats"><button class="btn btn-secondary btn-sm mx-1">Stats</button></a>            <a href="https://site.com/doc"><button class="btn btn-secondary btn-sm mx-1">API</button></a>        </div>        <span class="text-muted">© 2023 PLTFRM. All rights reserved. Version: <?php echo $version; ?></span>    </div></footer><!-- Bootstrap JS scripts --><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script><script>    // Функция для обновления таймера    function updateTimer() {        var deletionDate = <?php echo $file['date'] + $dayto * 24 * 60 * 60; ?>; // Добавляем 7 дня к времени загрузки файла        var now = Math.floor(Date.now() / 1000); // Текущее время в секундах
        var timeLeft = deletionDate - now;        if (timeLeft > 0) {            var days = Math.floor(timeLeft / (60 * 60 * 24));            var hours = Math.floor((timeLeft % (60 * 60 * 24)) / (60 * 60));            var minutes = Math.floor((timeLeft % (60 * 60)) / 60);            var seconds = Math.floor(timeLeft % 60);
            document.getElementById('timer').innerHTML = "Pre-deletion: " + days + "d " + hours + "h " + minutes + "m " + seconds + "s";        } else {            document.getElementById('timer').innerHTML = "Pre-deletion: File has been deleted";        }    }
    // Обновляем таймер каждую секунду    setInterval(updateTimer, 1000);</script><!-- Скрипт для отслеживания времени после нажатия на кнопку -->
<script>var downloadButton = document.getElementById('downloadLink');var downloadSection = document.getElementById('download-section');var timerInterval;var secondsElapsed = 0;
downloadButton.addEventListener('click', function (event) {    event.preventDefault(); // Отменяем стандартное действие кнопки
    // Начинаем отсчёт времени после нажатия на кнопку    timerInterval = setInterval(function () {        secondsElapsed++;        if (secondsElapsed === 10) {            clearInterval(timerInterval); // Останавливаем отсчёт после 10 секунд            // Показываем текст через 10 секунд, предлагающий альтернативную ссылку            downloadSection.innerHTML += '<p class="alert alert-info mt-3">Still not started downloading? <a href="download.php?id=<?php echo $file["file_id"]; ?>">Try this method</a></p>';        }    }, 1000);});
</script>
</body>

</html>